version: '3.7'
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=public_ip
      - PASSWORD_HASH=bcrypt_hashed_password
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - ./wireguard-data:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    restart: always